Update merge-master-beta.yml

diff --git a/.github/workflows/merge-master-beta.yml b/.github/workflows/merge-master-beta.yml
--- a/.github/workflows/merge-master-beta.yml
+++ b/.github/workflows/merge-master-beta.yml
@@ -29,26 +29,40 @@ jobs:
     #     github_token: ${{ secrets.MY_CUSTOM_TOKEN }}
     - name: Merge master into beta
       run: |
-        git checkout beta
-        if git merge --no-ff --no-commit --no-edit master; then
-            if ! git diff --quiet --cached; then
-                echo "Merge conflict occurred. Please resolve conflicts."
-                # Handle conflicts here if needed
-                git merge --abort && exit 1  # Abort the merge process
-            else
-                git commit -m "Merge changes from master into beta"
-                echo "Merge successful"
-                git push origin beta 
-            fi
-        else
-            echo "Merge failed"
-        fi
-    #     git checkout master
-    #     git fetch origin
-    #     git checkout beta
-    #     git pull
-    #     git merge --no-commit master || (echo "CONFLICT: Merge conflict detected" && git merge --abort && exit 1)
-    #     git push -u origin beta
+          git fetch origin master
+          git fetch origin beta
+          
+          # Checkout the beta branch
+          git checkout beta
+          
+          # Merge master into beta
+          if ! git merge --no-commit --no-ff origin/master; then
+              echo "Merge conflict detected. Aborting."
+              git merge --abort
+              exit 1
+          fi
+          
+          # Push changes to the beta branch
+          git push origin beta
+        # if git merge --no-ff --no-commit --no-edit master; then
+        #     if ! git diff --quiet --cached; then
+        #         echo "Merge conflict occurred. Please resolve conflicts."
+        #         # Handle conflicts here if needed
+        #         git merge --abort  # Abort the merge process
+        #     else
+        #         git commit -m "Merge changes from master into beta"
+        #         echo "Merge successful"
+        #         git push origin beta 
+        #     fi
+        # else
+        #     echo "Merge failed"
+        # fi
+        # git checkout master
+        # git fetch origin
+        # git checkout beta
+        # git pull
+        # git merge --no-commit master || (echo "CONFLICT: Merge conflict detected" && git merge --abort && exit 1)
+        # git push -u origin beta
 
     - name: Send Slack
       if: ${{ failure() }}
